jwt:
  secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

oauth:
  kakao:
    client-id: 551105433806ed2fe094c27f1e23b16d
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: tuEiThEu7f
    client-id: Bzg7vZ4K5M7Ks0_CwlMo
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
spring:
  datasource:
    url: jdbc:h2:mem:oauth2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
  h2:
    console:
      enabled: true
      path: /h2-console